-- Fix commands RLS to allow the Hub (target device owner) to update commands sent by Admin
DROP POLICY IF EXISTS "Users can manage their own commands" ON public.commands;

CREATE POLICY "Users can manage their own commands" ON public.commands 
FOR ALL USING (
  auth.uid() = user_id 
  OR 
  device_id IN (SELECT device_id FROM public.device_status WHERE user_id = auth.uid())
) WITH CHECK (
  auth.uid() = user_id 
  OR 
  device_id IN (SELECT device_id FROM public.device_status WHERE user_id = auth.uid())
);

-- Do the same for logs so Admin can see logs generated by AMIR's Hub
DROP POLICY IF EXISTS "Users can manage their own logs" ON public.logs;

CREATE POLICY "Users can manage their own logs" ON public.logs 
FOR ALL USING (
  auth.uid() = user_id 
  OR 
  device_id IN (SELECT device_id FROM public.device_status WHERE user_id = auth.uid())
  OR
  auth.email() = 'muhammadafif@upm.edu.my' -- Admin can read all logs
) WITH CHECK (
  auth.uid() = user_id 
  OR 
  device_id IN (SELECT device_id FROM public.device_status WHERE user_id = auth.uid())
);
